🤖 Starting RASA training pipeline at Tue Jun 24 15:48:05 UTC 2025
🔍 Validating training data...
/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/core/tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/shared/utils/validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/pkg_resources/__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "/Users/umitarslan/customer-care-ai/.venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/cli/data.py", line 122, in <lambda>
    func=lambda args: rasa.cli.utils.validate_files(
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/cli/utils.py", line 229, in validate_files
    from rasa.validator import Validator
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/validator.py", line 5, in <module>
    import rasa.core.training.story_conflict
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/core/training/story_conflict.py", line 6, in <module>
    from rasa.core.featurizers.tracker_featurizers import MaxHistoryTrackerFeaturizer
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/core/featurizers/tracker_featurizers.py", line 30, in <module>
    from rasa.core.featurizers.precomputation import MessageContainerForCoreFeaturization
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/core/featurizers/precomputation.py", line 16, in <module>
    from rasa.shared.nlu.training_data.features import Features
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/rasa/shared/nlu/training_data/features.py", line 9, in <module>
    from safetensors.numpy import save_file, load_file
  File "/Users/umitarslan/customer-care-ai/.venv/lib/python3.10/site-packages/safetensors/__init__.py", line 2, in <module>
    from ._safetensors_rust import (  # noqa: F401
ModuleNotFoundError: No module named 'safetensors._safetensors_rust'
❌ Data validation failed
